/* automatically generated by rust-bindgen 0.70.1 */

pub const CN_TYPE_NATIVE: u32 = 0;
pub const CN_TYPE_XPORT: u32 = 1;
pub const CN_TYPE_IEEEB: u32 = 2;
pub const CN_TYPE_IEEEL: u32 = 3;
extern "C" {
    pub fn cnxptiee(
        from_bytes: *const ::std::os::raw::c_void,
        fromtype: ::std::os::raw::c_int,
        to_bytes: *mut ::std::os::raw::c_void,
        totype: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
